import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
    container: {
        paddingVertical: 8,
        marginVertical: 4,
        width: "100%",
    },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 16,
        paddingHorizontal: 16,
    },
    title: {
        fontSize: 20,
        fontWeight: "700",
        color: "#1a1a1a",
        flexShrink: 0,
    },
    closeButton: {
        backgroundColor: "#FF4444",
        width: 28,
        height: 28,
        borderRadius: 14,
        justifyContent: "center",
        alignItems: "center",
        marginLeft: 12,
    },
    closeButtonText: {
        color: "white",
        fontSize: 16,
        fontWeight: "600",
    },
    scrollView: {
        maxHeight: 500,
        paddingHorizontal: 16,
    },
    inputGroup: {
        marginBottom: 20,
    },
    label: {
        fontSize: 16,
        fontWeight: "600",
        color: "#1a1a1a",
        marginBottom: 8,
    },
    dropdownContainer: {
        backgroundColor: "white",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#e9ecef",
        paddingHorizontal: 12,
        paddingVertical: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        height: 50,
    },
    dropdownText: {
        fontSize: 16,
        color: "#1a1a1a",
        flex: 1,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        justifyContent: "center",
        alignItems: "center",
    },
    dropdownModal: {
        backgroundColor: "white",
        borderRadius: 8,
        maxHeight: 300,
        width: "90%",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    dropdownList: {
        maxHeight: 300,
    },
    dropdownItem: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#f0f0f0",
    },
    selectedDropdownItem: {
        backgroundColor: "#f8f9fa",
    },
    dropdownItemContent: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    dropdownItemName: {
        fontSize: 16,
        fontWeight: "500",
        color: "#1a1a1a",
        flex: 1,
        marginRight: 8,
    },
    dropdownItemBalance: {
        fontSize: 14,
        fontWeight: "600",
        color: "#007AFF",
        marginRight: 8,
    },
    dropdownItemSymbol: {
        fontSize: 12,
        color: "#6c757d",
        fontWeight: "500",
        backgroundColor: "#f0f0f0",
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
    },
    textInput: {
        backgroundColor: "white",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#e9ecef",
        paddingHorizontal: 12,
        paddingVertical: 12,
        fontSize: 16,
        color: "#1a1a1a",
    },
    addressInputContainer: {
        flexDirection: "row",
        alignItems: "flex-end",
    },
    addressInput: {
        flex: 1,
        marginRight: 8,
        minHeight: 50,
        textAlignVertical: "top",
    },
    pasteButton: {
        backgroundColor: "#f8f9fa",
        borderRadius: 8,
        padding: 12,
        borderWidth: 1,
        borderColor: "#e9ecef",
    },
    balanceText: {
        fontSize: 14,
        color: "#6c757d",
        marginTop: 4,
        fontStyle: "italic",
    },
    validationText: {
        fontSize: 14,
        marginTop: 4,
        fontWeight: "500",
    },
    validText: {
        color: "#4CAF50",
    },
    invalidText: {
        color: "#F44336",
    },
    validInput: {
        borderColor: "#4CAF50",
        borderWidth: 2,
    },
    invalidInput: {
        borderColor: "#F44336",
        borderWidth: 2,
    },
    transferButton: {
        backgroundColor: "#007AFF",
        borderRadius: 8,
        paddingVertical: 16,
        paddingHorizontal: 20,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        marginTop: 20,
        marginBottom: 20,
    },
    disabledButton: {
        backgroundColor: "#ccc",
    },
    transferButtonText: {
        color: "white",
        fontSize: 16,
        fontWeight: "600",
        marginLeft: 8,
    },
    emptyContainer: {
        alignItems: "center",
        paddingVertical: 40,
        paddingHorizontal: 16,
    },
    emptyText: {
        fontSize: 16,
        color: "#6c757d",
        textAlign: "center",
    },
})
